### ISSUE TITLE
Wrong symlinks when fetch / checkout is done from symlinked folder

### ISSUE THREAD

**Issue by thorstenwagner** [kevin-hanselman/dud#158] opened 2023-08-21 06:39 UTC
Assume the following:

/a_dataset.yaml # this is my root directory
/A/a.txt

Now a.txt was updated.

If I run the following commands from root /, everything works fine:
```
rm /A/a.txt
dud fetch
dud checkout
```

If I run the following commands from /A/, the symlink to `a.txt` is broken:

```
rm a.txt
dud fetch
dud checkout
```

Best,
Thorsten

**Comment by kevin-hanselman** [comment] 2023-08-21 13:42
Hi @thorstenwagner. I need more information before I can reproduce this. 

> /a_dataset.yaml # this is my root directory

Do you mean this is your system's root directory (the absolute path `/`), or your project's root directory (where the `.dud` directory lives)?

> Now a.txt was updated.

Was it ever committed? How was it updated? Was it committed again after the update?

> `dud fetch`

Is `dud fetch` necessary to reproduce this issue? If so, what's your remote config? Where's `dud push`in this scenario?

When I assume the simplest scenario, I can't reproduce this:

``` sh
dud init
mkdir A
echo foo > A/a.txt
dud stage gen -o A/a.txt | tee a_dataset.yaml
dud stage add a_dataset.yaml
dud commit --copy
echo bar >> A/a.txt
dud commit
tree
rm A/a.txt
dud checkout
tree
cd A
rm a.txt
dud checkout
tree
```

Output:
```
Dud project initialized.
See .dud/config.yaml and .dud/rclone.conf to customize the project.
working-dir: .
outputs:
  A/a.txt: {}
Added a_dataset.yaml to the index.
committing stage a_dataset.yaml
  A/a.txt               4 B / 4 B  100%  ?/s  1ms total

committing stage a_dataset.yaml
  A/a.txt               8 B / 8 B  100%  ?/s  1ms total

.
├── A
│   └── a.txt -> ../.dud/cache/ab/b4ca7eb554f159c4970bf8c7c723b724ff9e88cfeb5ee5eec6894f67bcd86b
├── a_dataset.yaml
└── run.sh

2 directories, 3 files
checking out stage a_dataset.yaml
  A/a.txt               1 / 1  100%  ?/s  0s total

.
├── A
│   └── a.txt -> ../.dud/cache/ab/b4ca7eb554f159c4970bf8c7c723b724ff9e88cfeb5ee5eec6894f67bcd86b
├── a_dataset.yaml
└── run.sh

2 directories, 3 files
checking out stage a_dataset.yaml
  A/a.txt               1 / 1  100%  ?/s  0s total

.
└── a.txt -> ../.dud/cache/ab/b4ca7eb554f159c4970bf8c7c723b724ff9e88cfeb5ee5eec6894f67bcd86b

1 directory, 1 file
```

It would be most helpful if you could provide a Bash script, like this one, which completely reproduces this issue.

**Comment by thorstenwagner** [comment] 2023-08-21 14:25
A is my project directory, not my system root :-) Lets see if I can make it somehow reproducible.

**Comment by thorstenwagner** [comment] 2023-08-22 08:44
Kudo 2 @mstabrin , he made a reproducible example:

```bash
mkdir -p dudtest/mydud
ln -rs dudtest/mydud mydud
cd mydud
dud init
mkdir A
echo foo > A/a.txt
dud stage gen -o A/a.txt | tee a_dataset.yaml
dud stage add a_dataset.yaml
dud commit --copy
echo bar >> A/a.txt
dud commit
tree
rm A/a.txt
dud checkout
tree
cd A
rm a.txt
dud checkout
tree
```

![image](https://github.com/kevin-hanselman/dud/assets/1113977/08b5da43-2717-41f9-a78a-9eea6ecaf3f5)

**Comment by kevin-hanselman** [comment] 2023-08-26 15:02
Thanks for the example that I can run and reproduce! 

Having a project directory be a symlink is an unexpected use case. It's certainly not something I was planning to support, simply because I hadn't thought of it. I will poke at this a bit further, and if a fix is simple I will add it. But I can't guarantee support for a symlinked project directory. Can you help me understand the motivation behind this pattern?

**Comment by kevin-hanselman** [comment] 2023-08-26 15:09
My hunch is that [this](https://github.com/kevin-hanselman/dud/blob/992be8dcd5ed479f2bb2443ecd458a7369392c00/src/cmd/root.go#L220C18-L220C26) is the issue. From the [Go docs](https://pkg.go.dev/os#Getwd) (emphasis my own):

>Getwd returns a rooted path name corresponding to the current directory. **If the current directory can be reached via multiple paths (due to symbolic links), Getwd may return any one of them.**

**Comment by thorstenwagner** [comment] 2024-06-27 06:15
Would be really nice to see that fixed. I just happend again to me. I keep my training data separated from the actual training runs, instead I symlink the data. Now I was cd'ing into the symlinked data folder and add some new data. Now its broken again :-( 

btw, havent seen a commit for while. Is dud still maintained? If not, I need to find another alternative although I really love dud. Its just does what I need ^^

**Comment by kevin-hanselman** [comment] 2024-06-29 14:28
Hi @thorstenwagner! As I mentioned above, using symlinked root folders is [not recommended](https://github.com/kevin-hanselman/dud/issues/158#issuecomment-1694379615) in Dud due to a [limitation](https://github.com/kevin-hanselman/dud/issues/158#issuecomment-1694381339) in Go's `os.Getwd`. 

For now I will close this issue, but please use this thread to explain your project setup in more detail. If you do, I should be able to recommend an alternative configuration that mitigates this issue.

Regarding Dud being maintained, I have definitely not abandoned Dud; I still use it myself. But "maintained" means different things to different projects and people. What does maintained mean to you? Right now I am very busy with both work and life, and I haven't been able to commit to Dud (literally 😃) as much as I'd like. This being an open-source project, I am always happy to review and merge pull requests 😃.

**Closed by kevin-hanselman** 2024-06-29 14:28 UTC
Labels: bug

**Comment by thorstenwagner** [comment] 2024-06-30 20:28
> My hunch is that [this](https://github.com/kevin-hanselman/dud/blob/992be8dcd5ed479f2bb2443ecd458a7369392c00/src/cmd/root.go#L220C18-L220C26) is the issue. From the [Go docs](https://pkg.go.dev/os#Getwd) (emphasis my own):
> 
> > Getwd returns a rooted path name corresponding to the current directory. **If the current directory can be reached via multiple paths (due to symbolic links), Getwd may return any one of them.**
> 
> Consequently, I'm not sure how easy this will be to fix. I'll keep looking at it, though.

One idea for a workaround on linux systems: You could use the output of getcwd and then use os.exec to call `realpath OUTCWD`?
